pkgname=unity-2d

post_install() {
  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-mime-database usr/share/mime > /dev/null
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas
}

pre_upgrade() {
  pre_remove ${1}
}

post_upgrade() {
  post_install ${1}
}

pre_remove() {
  /bin/true
}
