post_install() {
    echo "If you want to use the global menus and you are not using Unity, you will need"
    echo "to add the following to ~/.config/gtk-3.0/settings.ini"
    echo
    echo "********************************"
    echo "[Settings]"
    echo "gtk-shell-shows-menubar = 1"
    echo "********************************"
}

pre_remove() {
    rm -f /usr/lib/gtk-3.0/3.0.0/immodules.cache
}
