SCHEMAS="compiz-unityshellrotated.schemas"

post_install() {
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas
  gconf-schemas --register ${SCHEMAS}
  update-gconf-defaults
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  gconf-schemas --unregister ${SCHEMAS}
  update-gconf-defaults
}

post_remove() {
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas
}
